[package]
name = "rtracing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
indicatif = "0.16.2"
image = "0.23.14"
